list: $/pensoft/workshops/models/workshop/columns.yaml
modelClass: Pensoft\Workshops\Models\Workshop
title: Workshops
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/workshops/workshops/update/:id'
